TESTS WITH ERRORS 
test12 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "/Users/k2i/academics/automatedgradingapp/app/testing/kb-inference/gradingtests.py", line 351, in test12
    self.assertTrue(str(answer1[0]).startswith("No bindings"))
IndexError: list index out of range

-------------------------------
TESTS FAILED  
test4 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "/Users/k2i/academics/automatedgradingapp/app/testing/kb-inference/gradingtests.py", line 98, in test4
    self.assertFalse(answer6)
AssertionError: True is not false

test5 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "/Users/k2i/academics/automatedgradingapp/app/testing/kb-inference/gradingtests.py", line 148, in test5
    self.assertFalse(answer3)
AssertionError: True is not false

-------------------------------
TESTS SKIPPED 
-------------------------------
